In [1]:
import pandas as pd
import os

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager

from selenium.webdriver.common.by import By # By es para buscar por tag, clase, id...
from selenium.webdriver.common.keys import Keys  

import time
from tqdm.notebook import tqdm

import warnings
warnings.filterwarnings('ignore')

In [2]:
#driver configuration
opciones=Options()

opciones.add_experimental_option('excludeSwitches', ['enable-automation'])
opciones.add_experimental_option('useAutomationExtension', False)
opciones.headless=False    # si True, no aperece la ventana (headless=no visible)
opciones.add_argument('--start-maximized')         # comienza maximizado
#opciones.add_argument('user-data-dir=selenium')    # mantiene las cookies
#opciones.add_extension('driver_folder/adblock.crx')       # adblocker
opciones.add_argument('--incognito')

In [3]:
#driver = "./chromedriver.exe" #remember substitute this for your driver path
#driver = webdriver.Chrome(driver,options = opciones)
PATH = ChromeDriverManager().install()     # instala el driver de chrome

driver=webdriver.Chrome(PATH, options = opciones)

In [4]:
url = 'https://www.nflpenalties.com/week/1?year=2022&view=log'

driver.get(url)

In [5]:
time.sleep(3)

driver.find_element(By.XPATH, '/html/body/div[5]/div[2]/div[1]/div[2]/div[2]/button[2]').click()

In [6]:
len(driver.find_elements(By.XPATH, '//th[@class="footable-sortable"]'))

16

In [7]:
cols = [e.text for e in driver.find_elements(By.XPATH, '//th[@class="footable-sortable"]')]
len(cols)

16

In [8]:
celdas = driver.find_elements(By.XPATH, '//td')[0:-16]
len(celdas)

3664

In [9]:
penalty = [celdas[i].text for i in range(0, len(celdas), 16)]
date = [celdas[i].text for i in range(1, len(celdas), 16)]
against = [celdas[i].text for i in range(2, len(celdas), 16)]
beneficiary = [celdas[i].text for i in range(3, len(celdas), 16)]
player = [celdas[i].text for i in range(4, len(celdas), 16)]
pos = [celdas[i].text for i in range(5, len(celdas), 16)]
ref_crew = [celdas[i].text for i in range(6, len(celdas), 16)]
quarter = [celdas[i].text for i in range(7, len(celdas), 16)]
time = [celdas[i].text for i in range(8, len(celdas), 16)]
down = [celdas[i].text for i in range(9, len(celdas), 16)]
distance = [celdas[i].text for i in range(10, len(celdas), 16)]
declined = [celdas[i].text for i in range(11, len(celdas), 16)]
offsetting = [celdas[i].text for i in range(12, len(celdas), 16)]
yards = [celdas[i].text for i in range(13, len(celdas), 16)]
home = [celdas[i].text for i in range(14, len(celdas), 16)]
phase = [celdas[i].text for i in tqdm(range(15, len(celdas), 16))]

  0%|          | 0/229 [00:00<?, ?it/s]

In [10]:
df = pd.DataFrame(columns=cols)

In [11]:
df['Penalty'] = penalty
df['Date'] = date
df['Against'] = against
df['Beneficiary'] = beneficiary
df['Player'] = player
df['Pos'] = pos
df['Ref Crew'] = ref_crew
df['Quarter'] = quarter
df['Time'] = time
df['Down'] = down
df['Distance'] = distance
df['Declined'] = declined
df['Offsetting'] = offsetting
df['Yards'] = yards
df['Home'] = home
df['Phase'] = phase

In [12]:
df.head()

,Penalty,Date,Against,Beneficiary,Player,Pos,Ref Crew,Quarter,Time,Down,Distance,Declined,Offsetting,Yards,Home,Phase
0,False Start,09/08/2022,LA Rams,Buffalo,D.Edwards,OL,Carl Cheffers,1,09:28,2,5,No,No,5,Yes,Offense
1,Horse Collar Tackle,09/08/2022,LA Rams,Buffalo,J.Hollins,LB,Carl Cheffers,1,01:53,1,10,No,No,15,Yes,Defense
2,Defensive Holding,09/08/2022,Buffalo,LA Rams,J.Phillips,DL,Carl Cheffers,2,07:20,1,10,No,No,5,No,Defense
3,Defensive Too Many Men on Field,09/08/2022,LA Rams,Buffalo,Unnamed,,Carl Cheffers,2,02:16,3,12,No,No,5,Yes,Defense
4,Defensive Holding,09/08/2022,Buffalo,LA Rams,T.Johnson,DB,Carl Cheffers,2,01:45,3,10,No,No,5,No,Defense

In [13]:
df2 = pd.read_excel('../boxscore.xlsx', engine='openpyxl')

In [14]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 285 entries, 0 to 284
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Week        284 non-null    object
 1   Day         284 non-null    object
 2   Date        285 non-null    object
 3   Time        284 non-null    object
 4   Winner/tie  284 non-null    object
 5   Unnamed: 5  123 non-null    object
 6   Loser/tie   284 non-null    object
 7   Unnamed: 7  284 non-null    object
 8   PtsW        283 non-null    float64
 9   PtsL        283 non-null    float64
 10  YdsW        283 non-null    float64
 11  TOW         283 non-null    float64
 12  YdsL        283 non-null    float64
 13  TOL         283 non-null    float64
dtypes: float64(6), object(8)
memory usage: 31.3+ KB

In [15]:
df2.index = range(len(df2))
df3 = df2.loc[df2['Week'] == 1]

In [16]:
df3.head()

,Week,Day,Date,Time,Winner/tie,Unnamed: 5,Loser/tie,Unnamed: 7,PtsW,PtsL,YdsW,TOW,YdsL,TOL
0,1,Thu,2022-09-08 00:00:00,8:20PM,Buffalo Bills,@,Los Angeles Rams,boxscore,31.0,10.0,413.0,4.0,243.0,3.0
1,1,Sun,2022-09-11 00:00:00,1:00PM,New Orleans Saints,@,Atlanta Falcons,boxscore,27.0,26.0,385.0,1.0,416.0,2.0
2,1,Sun,2022-09-11 00:00:00,1:00PM,Cleveland Browns,@,Carolina Panthers,boxscore,26.0,24.0,355.0,0.0,261.0,1.0
3,1,Sun,2022-09-11 00:00:00,1:00PM,Chicago Bears,NaN,San Francisco 49ers,boxscore,19.0,10.0,204.0,1.0,331.0,2.0
4,1,Sun,2022-09-11 00:00:00,1:00PM,Pittsburgh Steelers,@,Cincinnati Bengals,boxscore,23.0,20.0,267.0,0.0,432.0,5.0

In [17]:
df.Against.unique()

array(['LA Rams', 'Buffalo', 'Atlanta', 'New Orleans', 'Carolina',
       'Cleveland', 'San Francisco', 'Chicago', 'Cincinnati',
       'Pittsburgh', 'Detroit', 'Philadelphia', 'Indianapolis', 'Houston',
       'New England', 'Miami', 'N.Y. Jets', 'Baltimore', 'Washington',
       'Jacksonville', 'Arizona', 'Kansas City', 'Las Vegas',
       'LA Chargers', 'Minnesota', 'Green Bay', 'N.Y. Giants',
       'Tennessee', 'Tampa Bay', 'Dallas', 'Seattle', 'Denver'],
      dtype=object)

In [18]:
team_map_df = {'Arizona': 'ARI',
            'Atlanta': 'ATL',
            'Baltimore': 'BAL',
            'Buffalo': 'BUF',
            'Carolina': 'CAR',
            'Chicago': 'CHI',
            'Cincinnati': 'CIN',
            'Cleveland': 'CLE',
            'Dallas': 'DAL',
            'Denver': 'DEN',
            'Detroit': 'DET',
            'Green Bay': 'GB',
            'Houston': 'HOU',
            'Indianapolis': 'IND',
            'Jacksonville': 'JAC',
            'Kansas City': 'KC',
            'Las Vegas': 'LV',
            'LA Chargers': 'LAC',
            'LA Rams': 'LAR',
            'Miami': 'MIA',
            'Minnesota': 'MIN',
            'New England': 'NE',
            'New Orleans': 'NO',
            'N.Y. Giants': 'NYG',
            'N.Y. Jets': 'NYJ',
            'Philadelphia': 'PHI',
            'Pittsburgh': 'PIT',
            'San Francisco': 'SF',
            'Seattle': 'SEA',
            'Tampa Bay': 'TB',
            'Tennessee': 'TEN',
            'Washington': 'WAS'}

In [19]:
df3['Winner/tie'].unique()

array(['Buffalo Bills', 'New Orleans Saints', 'Cleveland Browns',
       'Chicago Bears', 'Pittsburgh Steelers', 'Houston Texans',
       'Philadelphia Eagles', 'Washington Commanders', 'Miami Dolphins',
       'Baltimore Ravens', 'Kansas City Chiefs', 'Minnesota Vikings',
       'New York Giants', 'Los Angeles Chargers', 'Tampa Bay Buccaneers',
       'Seattle Seahawks'], dtype=object)

In [20]:
df3['Loser/tie'].unique()

array(['Los Angeles Rams', 'Atlanta Falcons', 'Carolina Panthers',
       'San Francisco 49ers', 'Cincinnati Bengals', 'Indianapolis Colts',
       'Detroit Lions', 'Jacksonville Jaguars', 'New England Patriots',
       'New York Jets', 'Arizona Cardinals', 'Green Bay Packers',
       'Tennessee Titans', 'Las Vegas Raiders', 'Dallas Cowboys',
       'Denver Broncos'], dtype=object)

In [21]:
team_map_df3 = {'Arizona Cardinals': 'ARI',
            'Atlanta Falcons': 'ATL',
            'Baltimore Ravens': 'BAL',
            'Buffalo Bills': 'BUF',
            'Carolina Panthers': 'CAR',
            'Chicago Bears': 'CHI',
            'Cincinnati Bengals': 'CIN',
            'Cleveland Browns': 'CLE',
            'Dallas Cowboys': 'DAL',
            'Denver Broncos': 'DEN',
            'Detroit Lions': 'DET',
            'Green Bay Packers': 'GB',
            'Houston Texans': 'HOU',
            'Indianapolis Colts': 'IND',
            'Jacksonville Jaguars': 'JAC',
            'Kansas City Chiefs': 'KC',
            'Las Vegas Raiders': 'LV',
            'Los Angeles Chargers': 'LAC',
            'Los Angeles Rams': 'LAR',
            'Miami Dolphins': 'MIA',
            'Minnesota Vikings': 'MIN',
            'New England Patriots': 'NE',
            'New Orleans Saints': 'NO',
            'New York Giants': 'NYG',
            'New York Jets': 'NYJ',
            'Philadelphia Eagles': 'PHI',
            'Pittsburgh Steelers': 'PIT',
            'San Francisco 49ers': 'SF',
            'Seattle Seahawks': 'SEA',
            'Tampa Bay Buccaneers': 'TB',
            'Tennessee Titans': 'TEN',
            'Washington Commanders': 'WAS'}

In [22]:
df['Beneficiary'] = df['Beneficiary'].map(team_map_df)
df['Against'] = df['Against'].map(team_map_df)

df3['Winner/tie'] = df3['Winner/tie'].map(team_map_df3)
df3['Loser/tie'] = df3['Loser/tie'].map(team_map_df3)

In [23]:
df.head()

,Penalty,Date,Against,Beneficiary,Player,Pos,Ref Crew,Quarter,Time,Down,Distance,Declined,Offsetting,Yards,Home,Phase
0,False Start,09/08/2022,LAR,BUF,D.Edwards,OL,Carl Cheffers,1,09:28,2,5,No,No,5,Yes,Offense
1,Horse Collar Tackle,09/08/2022,LAR,BUF,J.Hollins,LB,Carl Cheffers,1,01:53,1,10,No,No,15,Yes,Defense
2,Defensive Holding,09/08/2022,BUF,LAR,J.Phillips,DL,Carl Cheffers,2,07:20,1,10,No,No,5,No,Defense
3,Defensive Too Many Men on Field,09/08/2022,LAR,BUF,Unnamed,,Carl Cheffers,2,02:16,3,12,No,No,5,Yes,Defense
4,Defensive Holding,09/08/2022,BUF,LAR,T.Johnson,DB,Carl Cheffers,2,01:45,3,10,No,No,5,No,Defense

In [24]:
df3.head()

,Week,Day,Date,Time,Winner/tie,Unnamed: 5,Loser/tie,Unnamed: 7,PtsW,PtsL,YdsW,TOW,YdsL,TOL
0,1,Thu,2022-09-08 00:00:00,8:20PM,BUF,@,LAR,boxscore,31.0,10.0,413.0,4.0,243.0,3.0
1,1,Sun,2022-09-11 00:00:00,1:00PM,NO,@,ATL,boxscore,27.0,26.0,385.0,1.0,416.0,2.0
2,1,Sun,2022-09-11 00:00:00,1:00PM,CLE,@,CAR,boxscore,26.0,24.0,355.0,0.0,261.0,1.0
3,1,Sun,2022-09-11 00:00:00,1:00PM,CHI,NaN,SF,boxscore,19.0,10.0,204.0,1.0,331.0,2.0
4,1,Sun,2022-09-11 00:00:00,1:00PM,PIT,@,CIN,boxscore,23.0,20.0,267.0,0.0,432.0,5.0

In [25]:
winners = [e for e in df3['Winner/tie']]
losers = [e for e in df3['Loser/tie']]

In [26]:
df['Winner'] = None
df['Loser'] = None

for i in range(len(df['Against'])):
    if df['Against'][i] in winners:
        df['Winner'][i] = df['Against'][i]
    elif df['Against'][i] in losers:
        df['Loser'][i] = df['Against'][i]

for i in range(len(df['Beneficiary'])):
    if df['Beneficiary'][i] in winners:
        df['Winner'][i] = df['Beneficiary'][i]
    elif df['Beneficiary'][i] in losers:
        df['Loser'][i] = df['Beneficiary'][i]

In [27]:
df.head()

,Penalty,Date,Against,Beneficiary,Player,Pos,Ref Crew,Quarter,Time,Down,Distance,Declined,Offsetting,Yards,Home,Phase,Winner,Loser
0,False Start,09/08/2022,LAR,BUF,D.Edwards,OL,Carl Cheffers,1,09:28,2,5,No,No,5,Yes,Offense,BUF,LAR
1,Horse Collar Tackle,09/08/2022,LAR,BUF,J.Hollins,LB,Carl Cheffers,1,01:53,1,10,No,No,15,Yes,Defense,BUF,LAR
2,Defensive Holding,09/08/2022,BUF,LAR,J.Phillips,DL,Carl Cheffers,2,07:20,1,10,No,No,5,No,Defense,BUF,LAR
3,Defensive Too Many Men on Field,09/08/2022,LAR,BUF,Unnamed,,Carl Cheffers,2,02:16,3,12,No,No,5,Yes,Defense,BUF,LAR
4,Defensive Holding,09/08/2022,BUF,LAR,T.Johnson,DB,Carl Cheffers,2,01:45,3,10,No,No,5,No,Defense,BUF,LAR

In [28]:
df4 = pd.read_csv('../2022 NFL Schedule - Week 1.csv')

In [29]:
df4 = df4.rename(columns={
    "Unnamed: 0": "cero",
    "Unnamed: 1": "Away Team",
    "Unnamed: 2": "dos",
    "Unnamed: 3": "Home Team",
    "Unnamed: 4": "cuatro",
    "Unnamed: 5": "Time"
})

In [30]:
df4 = df4.dropna(axis=1, how='all')
df4 = df4.drop_duplicates()
df4 = df4.drop(columns = ["cero", "dos", "cuatro"])
df4 = df4.dropna(axis=0, how='all')
df4 = df4.reset_index(drop=True)

In [31]:
df4['Primetime'] = 'NO'

for i in [1, 16, 18]:
    df4.loc[i, 'Primetime'] = 'YES'

In [32]:
df4.drop([0, 2, 17], inplace=True)

In [33]:
df4.reset_index(drop=True, inplace=True)

In [34]:
df4.head()

              Away Team           Home Team       Time Primetime
0         Buffalo Bills    Los Angeles Rams  8:20 p.m.       YES
1    New Orleans Saints     Atlanta Falcons  1:00 p.m.        NO
2   San Francisco 49ers       Chicago Bears  1:00 p.m.        NO
3   Pittsburgh Steelers  Cincinnati Bengals  1:00 p.m.        NO
4  New England Patriots      Miami Dolphins  1:00 p.m.        NO

In [35]:
df4['Away Team'] = df4['Away Team'].map(team_map_df3)
df4['Home Team'] = df4['Home Team'].map(team_map_df3)

In [36]:
mask1 = df4['Primetime'] == 'YES'
primetimers1 = df4.loc[mask1, 'Home Team'].tolist()

mask2 = df4['Primetime'] == 'YES'
primetimers2 = df4.loc[mask2, 'Away Team'].tolist()

primetimers = primetimers1 + primetimers2
primetimers

['LAR', 'DAL', 'SEA', 'BUF', 'TB', 'DEN']

In [37]:
df['Prime Time'] = None

for i in range(len(df['Prime Time'])):
    if df['Beneficiary'][i] in primetimers:
        df['Prime Time'][i] = 'YES'
    else:
        df['Prime Time'][i] = 'NO'

In [38]:
df.head()

,Penalty,Date,Against,Beneficiary,Player,Pos,Ref Crew,Quarter,Time,Down,Distance,Declined,Offsetting,Yards,Home,Phase,Winner,Loser,Prime Time
0,False Start,09/08/2022,LAR,BUF,D.Edwards,OL,Carl Cheffers,1,09:28,2,5,No,No,5,Yes,Offense,BUF,LAR,YES
1,Horse Collar Tackle,09/08/2022,LAR,BUF,J.Hollins,LB,Carl Cheffers,1,01:53,1,10,No,No,15,Yes,Defense,BUF,LAR,YES
2,Defensive Holding,09/08/2022,BUF,LAR,J.Phillips,DL,Carl Cheffers,2,07:20,1,10,No,No,5,No,Defense,BUF,LAR,YES
3,Defensive Too Many Men on Field,09/08/2022,LAR,BUF,Unnamed,,Carl Cheffers,2,02:16,3,12,No,No,5,Yes,Defense,BUF,LAR,YES
4,Defensive Holding,09/08/2022,BUF,LAR,T.Johnson,DB,Carl Cheffers,2,01:45,3,10,No,No,5,No,Defense,BUF,LAR,YES

In [39]:
df = df.drop(columns = ["Date", "Player", "Declined", "Offsetting"])

In [40]:
df.loc[df['Pos'] == '', 'Pos'] = 'NP'

In [41]:
df[["Quarter", "Down", "Distance", "Yards"]] = df[["Quarter", "Down", "Distance", "Yards"]].astype(int)

In [42]:
df['Time'] = df['Time'].apply(lambda x: int(x.split(":")[0]) * 60 + int(x.split(":")[1]))

In [43]:
df = df.rename(columns = {'Time': 'Time left'})

In [44]:
df['Time left'] = df['Time left'].astype(int)

In [45]:
for c in df.select_dtypes('integer'):
    
    df[c]=pd.to_numeric(df[c], downcast='integer')

In [46]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229 entries, 0 to 228
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Penalty      229 non-null    object
 1   Against      229 non-null    object
 2   Beneficiary  229 non-null    object
 3   Pos          229 non-null    object
 4   Ref Crew     229 non-null    object
 5   Quarter      229 non-null    int8
 6   Time left    229 non-null    int16
 7   Down         229 non-null    int8
 8   Distance     229 non-null    int8
 9   Yards        229 non-null    int8
 10  Home         229 non-null    object
 11  Phase        229 non-null    object
 12  Winner       229 non-null    object
 13  Loser        229 non-null    object
 14  Prime Time   229 non-null    object
dtypes: int16(1), int8(4), object(10)
memory usage: 141.1 KB

In [47]:
from sqlalchemy import create_engine

# cargar archivo de contraseñas

with open('../password.txt', 'r') as file:
    
    passwd = file.read().split('\n')[0]

str_conn = f'mysql+pymysql://root:{passwd}@localhost:3306/nflpenalties'
cursor = create_engine(str_conn)

df.to_sql('penalties_week_1_2022',con=cursor, if_exists='append', index=False)

229

In [48]:
df.to_csv('../penalties_week_1')